// server/models/InvestorSession.js
const mongoose = require('mongoose');

const AnswerSchema = new mongoose.Schema({
  question:    { type: String, required: true },
  userAnswer:  { type: String, required: true },
  aiFeedback:  { type: String, required: true },
  answeredAt:  { type: Date, default: Date.now },
});

const InvestorSessionSchema = new mongoose.Schema({
  user:          { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  investorType:  String,
  fundingStage:  String,
  domain:        String,
  questions:     [String],        // generated by AI
  answers:       [AnswerSchema],  // new: stores each Q&A turn
  createdAt:     { type: Date, default: Date.now },
});

module.exports = mongoose.model('InvestorSession', InvestorSessionSchema);

